# Generated by Django 4.0 on 2024-12-08 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('address', models.TextField(verbose_name='Billing Address')),
                ('payment_method', models.CharField(choices=[('mpesa', 'Mpesa')], max_length=20, verbose_name='Payment Method')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Transaction ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Transaction Date and Time')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Course Title')),
                ('description', models.TextField(verbose_name='Course Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Course Price')),
                ('seats_available', models.IntegerField(default=0, verbose_name='Available Seats')),
            ],
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.AddField(
            model_name='checkout',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutor.course', verbose_name='Selected Course'),
        ),
    ]
