# Generated by Django 4.0 on 2024-12-09 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0002_checkout_course_imagemodel_delete_appointment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='checkout',
            name='mpesa_number',
            field=models.CharField(default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutor.course'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='payment_method',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
