# Generated by Django 4.0 on 2024-12-09 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0003_remove_checkout_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='address',
        ),
    ]
