# Generated by Django 4.0 on 2024-12-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0005_remove_checkout_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
            ],
        ),
    ]
